### ISSUE TITLE
Support 0+ genes per variant, 0+ variants per gene

### ISSUE THREAD

**Issue by Relequestual** [ga4gh/mme-apis#114]
When a merge happened to pull in the gene attribute to the genomicFeatures attribute, the gene was made manditory, while it was inteneded for the gene to remain optional. A gene OR variant should be manditory, which caters of CNV data. While Decipher has both SNV and CNV data, CNV data will not have an attached gene.

Merge commit in question which shows this: https://github.com/MatchmakerExchange/mme-apis/commit/064326aca62dbe59daa996befff9c8c6523b40d4

**Comment by buske** [comment]
Hmm, I thought the intent was to have that be mandatory, but I agree this doesn't cater to CNV data. This brings up an important question: "Do we want genomic matching to be oriented around genes or not?" 

I was working under the assumption that, at least in the near future, genomic matching in the MME will operate at the level of matching on genes and gene-associated features. This obviously has issues in the long term. What about non-coding variants, CNVs, or large-scale rearrangements? Or variants in enhancers in nearby genes (e.g. lactase expression is regulated by mutations in the intron of a nearby gene)?

It really depends on what the scope of the API is. If we're focusing on clinical data where genomic features have been curated to some extent, then there is almost always going to be one (or more) genes involved. For a CNV, it's some subset of the genes it overlaps. Presumably you'd want to find other patients with mutations in those genes. For a variant, it's the gene it's in, or the gene it's suspected of modifying. Alternatively, if we want to move towards truly hypothesis-free matching, then our goal really is to characterize a patient as accurately as possible, at which point we should just support arbitrary VCF-like variant descriptions (i.e. GA4GH Variant objects).

**Comment by fschiettecatte** [comment]
For GM it would not make sense to make the variant mandatory, but we would be ok with making it mandatory to have other the gene or the variant. As for matching, I think that is something to leave up to individual sites. We match on both the gene and the variant, whichever is presented, and we will adjust if needed as we go forward.

**Comment by mellybelly** [comment]
Why not allow matching only on phenotypes? what if there are very many candidate variants or no good ones?

**Comment by fschiettecatte** [comment]
The protocol allows that, the client can send whatever information it wants in the request, we just make it a requirement to have a minimal amount of information for a viable request. The server in turn is free to run the match how it wants. For example GeneMatcher matches on the disease and genes, and in the near future we will be adding matching on features too. It is important for the protocol not to mandate how the match is made so that different servers can implement different approaches best suited to the data they store.

**Comment by buske** [comment]
Okay, I see I got carried away. Sorry. Too much time working on the paper and thinking philosophically. Yes, I agree that we should have it be mandatory that at least one of gene or variant be specified for a genomicfeature.

**Comment by Relequestual** [comment]
Agreed.

I believe I understand what you're saying @buske. 

We moved our internal "overlapping patients" functionality (and now also internal matchmaker alerting system) to do functional overlap as opposed to positional. We define this functional overlap as a combination of a variant ***gene*** and ***consequence***. We have a matrix of scores for the type of consequence against another. On this table we have included cnv_gain and cnv_loss, with a generally low score. Practically I'm not sure if that's useful to others, but that's how we currently handle this issue.

For our current release, what I will do is disable all CNVs from being included in requests Decipher is making. Although be prepared for CNVs being returned, which will not have a gene.

Long term: If we were to run a CNV through the VEP (Varient Effect Prediction) tool, it does return a conseuqence for each overlapping gene. We could use this consequence information to pick out potential candidate genes, and in addition have a threshold for HI score (Haplo Insaficiancy Score http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2954820/). I know previously @buske mentioned that you use some method for prioritising genes? Apoligies I forget what it was called.

If we were to allow for CNV level data (which I think we should), then there are two options I can immediatly see. Either multiple geneomicFeature elements, each with a different gene and consequence. OR, ***gene*** would be changed to an array of ***genes***, allowing for the ***type*** (consequence) to be nested under each gene.

I'm going to move this to 1.1 milestone as opposed to before 1.1, because I think I have a workable solution in dissallowing CNVs to be included in queries for now.

**Comment by Relequestual** [comment]
MME Technical group call dated 4th Aug.

Agreed we can specifiy multiple genes per variant. Also allow for gene or variant as opposed to gene being required.

Look at how ga4gh is doing "varint" and "variant annotation" first.
(Decipher may want to look at automated prediction for automatically selecting genes for larger cnvs. @orion to follow up with information on how they do this with whole exome level data)

**Comment by buske** [comment]
PhenomeCentral uses a tool called the [Exomiser](https://www.sanger.ac.uk/resources/software/exomiser/) to prioritize genes based on the patient's phenotype and the VCF data.

The sequence annotation classes are no longer part of master (instead on the metadata branch), but I believe the GA4GH `Feature` class is intended to be able to capture gene definitions, such as for the purposes of representing an entry in a BED or GFF file (with the `FeatureSet` class corresponding to the whole file). However, I can't find an example of linking such a gene to an existing entity like a variant. My guess is that an OntologyTerm-like approach would be fine (e.g. `database`, `identifier`, `label`, `version`).

**Comment by buske** [comment]
@Relequestual - I think a PR is on your plate for this issue.

**Comment by Relequestual** [comment]
Noted and self assigned. It's on my radar, but not sure how soon I can get to it due to other deadlines

**Comment by Relequestual** [comment]
I'm going to close this issue and associated PR as we have resolved including CNVs in a different way.

CNVs are only discoverable if they only overlap at most two genes. Otherwise, they are not discoverable.
