### ISSUE TITLE
Formalize "_"-prefix for non-standard fields

### ISSUE THREAD

**Issue by buske** [ga4gh/mme-apis#117]
This is the approach used by GeneMatcher. The API is currently silent on the topic. I think we should formally advocate this convention.

**Comment by fschiettecatte** [comment]
+1

**Comment by Relequestual** [comment]
+1

**Comment by tudorgroza** [comment]
Apologies for jumping like this into the discussion ... any chance for an example?

**Comment by fschiettecatte** [comment]
Here you go:

```JSON
    "gene": {
        "_ensemblGeneID": "ENSG00000133392", 
        "_entrezGeneID": "4629", 
        "_geneName": "MYH11", 
        "id": "ENSG00000133392"
    }, 
```

**Comment by tudorgroza** [comment]
Thank you @fschiettecatte . To continue my naive series of questions ... why would one formalise a prefix, instead of providing a proper formalisation to the actual data structure supported by the endpoint? 
@buske : I think the sort of effort we started discussing about - i.e., creating formal / machine-interpretable descriptions for endpoints - makes more and more sense. This ties in also with the CURIEs and 'official' gene IDs supported by the different endpoints. More than happy do discuss this further.

**Comment by Relequestual** [comment]
I think the idea is to allow for a pair of databases to test the usibility of potential new API funcionality without the need for it to be part of the specification.

@tudorgroza re your second point: I'm currently working on perl support for draf4 json-schema (It's already there in many other langauges). json-schema includes hyper-schema, which can be used to define API's like so https://brandur.org/elegant-apis#hyper-schema

Unlike AVRO (as far as I'm aware), json-schema has a test suite which a large percentage of the libraries across different languages use to confirm interoperability and compliance!

**Comment by cmungall** [comment]
I'm not keen on the underscore prefix but if this is just for testing (why not have normal field names on a branch? Or just document it as being for testing?)

The more important thing is that IDs must be unambiguous and should have a single way of being written. If you have a field "id" then you be guaranteed someone will put an integer in there, with no way of knowing if this is HUGO, NCBI Gene, ...

The way to avoid this is either CURIE (consistently prefixed ID) or building the database unambiguous into the property field.

**Comment by Relequestual** [comment]
As I understand, it's to allow databases to try things without the need to document accordingly.

**Comment by Relequestual** [comment]
I'm pretty sure the issue regarding IDs is a very seperate issue to this one.

https://github.com/ga4gh/mme-apis/issues/113 maybe. Or feel free to create a new issue.

**Comment by tudorgroza** [comment]
Given that in most cases - or at least those related to the core data - the IDs refer to ontological concepts, it would be ideal to use a representation format as close as possible to these native concepts. In this way, we could encode the semantics in the definition - in a non-static manner - and enable more complex constructs - such as IDx is defined as a subclass of HP:xxxxx (Phenotypic abnormality). Furthermore, this would allow matchmakers to use diverse datasets / IDs for the same type of data, at different points in time, without 'hardcoding' the definition of the provenance of the IDs, and would push the matching / mapping task (of this data) onto the query initiators.

**Comment by Relequestual** [comment]
I'm not 100% sure what you mean by this, but I'm pretty sure that it's not related to the issue at hand. This issue is about using an underscore prefix to field names, so a database can add fields that are not officially specified. The example happened to be releated fields, but it could be anything, not specifically ID based fields.

**Comment by fschiettecatte** [comment]
I second @Relequestual's comments, this thread is for "_" prefixes and not CURIEs, that discussion is at https://github.com/ga4gh/mme-apis/issues/113. 

As the originator of the "_" prefixes in GeneMatcher (@buske created this formalization), I recommend dropping the whole thing, it seems to have created more confusion than anything else. It was supposed to be a debugging aid, but all to it seem to have created are bugs.

**Comment by buske** [comment]
Indeed, this thread seems to have strayed. I'll try to clarify, but otherwise we can just drop the issue.

@tudorgroza @cmungall: It seems my initial description was vague and has caused some confusion. This has nothing to do with IDs. Here is another example from the current testing data on master (since the PR to fix it is still stalled):
```
"variant": {
  "assembly": "GRCh37",
  "hgvs": "NM_004247.3(EFTUD2):c.2770C>T",
  "referenceName": "17",
  "start": 42929131
}
```
The `"hgvs"` field there is non-standard, and was included because the information was available, and may be incredibly useful for debugging or for particular hgvs-based matchmakers (e.g. DECIPHER was parsing it). It was not a sufficiently common requirement to warrant creating an official optional field in the API. 

This Issue was a proposal to formally support the following instead (note the underscore before the "hgvs" field name):
```
"variant": {
  "assembly": "GRCh37",
  "_hgvs": "NM_004247.3(EFTUD2):c.2770C>T",
  "referenceName": "17",
  "start": 42929131
}
```

More explicitly, the use case is: I am a Matchmaker and have some additional data that is not currently supported formally within the API, but I would like to include to enable better matching with other Matchmakers that support it or help debugging any problems. I see several ways of addressing this:

1. Only the fields in the API are supported. The presence of any non-standard fields is a validation error.
    - Pro: everyone can see exactly what fields are supported
    - Cons: must validate absence of any other fields; no way to include additional helpful data without approval by all of MME; no way to see what fields people are already wanting to include in the API but are not yet formalized

2. Non-standard fields are fine ("if you don't parse them, don't worry about them"), and there is no specific convention to distinguish them. **We initially agreed to this.**
    - Pros: simple; no need to parse them
    - Cons: no visual distinction between official fields and non-standard fields; typos in field names will not raise any flags

3. Add some prefix or suffix to these non-standard field names. This is equivalent to the vendor suffixes in CSS (e.g. "-webkit") and the underscore prefix in Python (e.g. "_internalField").
    - Pros: relatively simple; allows validating against typos in supported fields; clear which fields are non-standard
    - Cons: allows non-standard fields in the API, which may cause some confusion

**Comment by Relequestual** [comment]
I'm pretty sure we're agreed on this issue. PR required.

**Comment by fschiettecatte** [comment]
I guess the onus is on me to figure out how to do a pull request.

**Comment by buske** [comment]
I +1'd and merged the PR, so marking this as resolved.

**Comment by buske** [comment]
By the way, thanks for doing a PR, @fschiettecatte! Looked great!
