### ISSUE TITLE
Add links to any existing public implementations of the API to README.md

### ISSUE THREAD

**Issue by bw2** [ga4gh/mme-apis#118]
Since many parameters are optional in the API it's possible to imagine many different approaches to the matching algorithm. It would be useful to see how existing implementations approach this.

**Comment by Relequestual** [comment]
Maybe we should link to the Human Mutation special edition papers... when they come out. I know the paper from Decipher will be open access.

**Comment by Relequestual** [comment]
All the papers are out now. Should we make more of a point to link to the MME website and papers from the readme here?

**Comment by buske** [comment]
I've added links to existing implementations to the README (90c6ba8a74a0fbb0ebe1939962a987cee8eb5233), so am closing this issue. @Relequestual, I agree we should point to the main MME website as well. If you could create a PR for that (or just commit to master), that'd be awesome!
