### ISSUE TITLE
Versioning patient data included in match request/response

### ISSUE THREAD

**Issue by buske** [ga4gh/mme-apis#119]
Currently, the patient `id` should not change over time, even if the data in the record does change. This `id` can be used by services to ensure that redundant emails aren't sent out if the same match request is sent again. However, if the patient data changes, services may want to send a new email, and being able to uniquely identify a patient record at a particular point in time is necessary for proper provenance.

Therefore, I'd suggest we include a field for the last-modified date or version number for the patient. The pair of `id` + `version`/`lastModified` would then uniquely specify the particular data in a match request/response.

Thoughts? Do all services support changing the data in the record? Is there a preference between `version` and `lastModified`?

**Comment by pdl** [comment]
DECIPHER stores a last modified field, though many changes won't affect MME results (e.g. changes to fields which are not displayed by MME or changes to fields only visible to the depositor). It's probably easier enough to make a version which is just an integer timestamp.

Two things to bear in mind when deciding how to use this:

- Requesting a specific historical version of a patient record may be impossible (for DECIPHER there's no way to automatically view a patient's record as it was at a given timestamp).
- Also worth considering: for a given query, scores might change in the absence of patient data changing (e.g. if the scoring model is changed or if the scoring model is based on e.g. number of patients in the DB).

**Comment by fschiettecatte** [comment]
GeneMatcher stores a last modified field as well, and am ok with using an integer timestamp.

**Comment by Relequestual** [comment]
+1
This would be creating a sort of hash as opposed to a version ID, which can't be looked up againt to retrieve that exact version of the patient.

**Comment by fschiettecatte** [comment]
I'll add a couple of comments. It may be an idea to use a date so that you can inform the submitters as to when the data was updated. The other is that GeneMatcher does not re-present matches that were made in the past, we assume that the two submitters have talked about the match and will do so again if data gets updated in the future.

**Comment by buske** [comment]
Okay, thank you all for your comments. Any opposition to supporting both (string) version and (ISO 8601 datetime) last-modified?

@pdl - Those are both good points. It is by no means a perfect system, but I think the more version information we start collecting, the better off we are. Not all systems will allow looking up a patient by a version, but some do (e.g. PhenomeCentral), and transmitting that information could be very helpful.

@Relequestual - Is that a +1 of the hash/version ID or for a timestamp or both?

**Comment by fschiettecatte** [comment]
No objections here.

**Comment by Relequestual** [comment]
Currently I think a hash. There are some internal issues that will need to be discussed before Decipher could commit to this. @pdl to update, as I will shortly be on leave.

**Comment by pdl** [comment]
Following up on @Relequestual's comment, unfortunately, it turns out that the contents of the last modified field aren't among the data that DECIPHER currently has the right to share via MME.

> However, if the patient data changes, services may want to send a new email, and being able to uniquely identify a patient record at a particular point in time is necessary for proper provenance.

Something that was suggested for this use case when we talked about it was client services taking the important data (being data which would cause you to do something different when it changed) from the response and taking a hash of it, then storing it and comparing a new hash against the old one. That way you can tell if the data has changed in a way which would actually cause you to behave differently. That is likely to be a lot more helpful than whether the patient record itself has changed.

**Comment by buske** [comment]
If it really is just a hash of the data included in the request, then is there any reason for adding this to the API? The receiving server could just compute it, or directly diff requests. 

- Last-modified tells you something about the recency of the data. 
- A hash of only the data being transferred seems redundant to me. 
- A hash of the whole patient record provides an effective ID without conveying recency.

**Comment by Relequestual** [comment]
True. The receiving party could compute a hash each time a patient is recieved and store that value. Considering that the "last updated" field may not be information everyone can share via the API (as Decipher cannot), suggesting that those who wish to be able to uniqly identify patients so as to not send out duplicate emails / notifications store a hash of the data, seems like a reasonable solution to the problem.

Actually, this is probably better than defining what elements should compose the hash, as each system can hash the data that it considers useful / valuiable, and it's not dependant on the API version.

**Comment by Relequestual** [comment]
Vote to close as will not fix / implement (new tag "will not implement"?)

**Comment by fschiettecatte** [comment]
+1

**Comment by Relequestual** [comment]
Agreed via technicall call being held as writing, closing.
