### ISSUE TITLE
Create separate email and url fields for 1.1

### ISSUE THREAD

**Issue by jxchong** [ga4gh/mme-apis#128]
Create separate fields for providing URL and email contact in MME requests. That way we don't have to stick both in the same contact field. Created per @Relequestual request :)

**Comment by buske** [comment]
+1

**Comment by Relequestual** [comment]
+1

**Comment by Relequestual** [comment]
@buske I can't remember if we decided this would be backwards compatible or not during the meeting. I feel it would be if we said the new optional field MUST contain a URL, while the ID field SHOULD not be a URL.

**Comment by fschiettecatte** [comment]
We did decide that it should be compatible, and your language covers that.

**Comment by fschiettecatte** [comment]
Following the Baltimore MME meeting, this was formalized and accepted for 1.1
