### ISSUE TITLE
Disclaimer in response

### ISSUE THREAD

**Issue by Relequestual** [ga4gh/mme-apis#129]
I think some systems are already adding their disclaimer in the response as an unofficial additional field using the underscore syntax.

We could add this for 1.1.

**Comment by fschiettecatte** [comment]
GeneMatcher adds a “_disclaimer” field at the top level of both request and response, I would suggest making this official as “disclaimer” and make it an optional field.

**Comment by fschiettecatte** [comment]
So it does not drop off the list, @Relequestual suggested adding 'terms' alongside 'disclaimer', see:[https://github.com/ga4gh/mme-apis/issues/140](url)

**Comment by Relequestual** [comment]
Decipher will be adding an `_disclaimer` with our next release.

**Comment by fschiettecatte** [comment]
Following Baltimore MME meeting:

`_disclaimer` is formalized to  `disclaimer` and we are adding `terms` as well. Both are optional, live in the root object, and can be included with every request and response.

**Comment by Relequestual** [comment]
I think `terms` was only needed for the stats endpoint, and not the core MME API response object.

**Comment by fschiettecatte** [comment]
True, I remember now, might just be easier to generalize these across the endpoint for consistency & simplicity, they are optional.
