### ISSUE TITLE
Add date created / date updated to submissions

### ISSUE THREAD

**Issue by fschiettecatte** [ga4gh/mme-apis#131]
It would be a good idea to add date created / date updated to each patient so users know how new/old the information is.

**Comment by buske** [comment]
+1

Best,
Orion

**Comment by Relequestual** [comment]
What's the use case for knowing such information? I believe we talked about this before and there was a reason against, but I can't remember what it was.

**Comment by fschiettecatte** [comment]
Ada said that this could inform someone of how 'relevant' the information is based on how old it is. However in subsequent discussions with Nara it is less clear that there is a correlation between date and relevance.

**Comment by Relequestual** [comment]
I THINK DECIPHER wouldn't want to divulge such data.

**Comment by buske** [comment]
I think PhenomeCentral would be okay with sharing this, if it is of interest to other groups.

**Comment by jxchong** [comment]
MyGene2 would be ok with sharing this but I'm not sure how useful it would be.

**Comment by fschiettecatte** [comment]
I think this one died on September 7th...

**Comment by Relequestual** [comment]
I think someone may infer usefulness about the record because of the date, which we established above, could be an invalid inference to make. Could it do more harm than good?

**Comment by buske** [comment]
If anyone feels strongly that this would be useful, please re-open.
