### ISSUE TITLE
Decipher returns 400 if features is empty list

### ISSUE THREAD

**Issue by buske** [ga4gh/mme-apis#132]
@Relequestual It looks like the Decipher endpoint is returning a 400 if  `"features": []` is included in the query patient. When I remove that (just leaving the candidate gene), I get the response. Ironically, in the response was a Decipher patient, https://decipher.sanger.ac.uk/patient/332404, without any phenotypes, which was serialized in the response as `"features": []`. :)

I'd suggest endpoints be tolerant to an empty list for `features` and `genomicFeatures` and make sure this is clear in the spec.

**Comment by jxchong** [comment]
++

**Comment by Relequestual** [comment]
It is manditory to have at least `features` or `genemicFeatures`. I agree it isn't clear in the spec that the array must contain at least one element.
I decided it makes more sense this way when trying to have a logical definition. If I must have at least one of `features` or `genemicFeatures`, then also the value of these must be a non empty array, having at least one item. The logical definition gets more complicated if you want to define that you must have at least one of `features` or `genemicFeatures` where an empy array is a valid value, but one of them must be a non empty array.

**Comment by Relequestual** [comment]
I agree that our response of an empty features array is not good though! I'll look into that.

**Comment by buske** [comment]
@Relequestual, sorry, I don't think I was clear. To clarify, `genomicFeatures` was provided and contained a candidate gene. This was regarding whether not `features` was **also** provided. More explicitly:

When I query DECIPHER with a patient with:
 `"genomicFeatures":[{"gene":{"id":"GENEX"}}], "features":[]`
I get a 400.

When I query DECIPHER with a patient with: 
`"genomicFeatures":[{"gene":{"id":"GENEX"}}]`
I get matches back, including one that contains: `"genomicFeatures":[{"gene":{"id":"GENEX"}}], "features":[]`.

I actually think an empty array should be supported.

**Comment by Relequestual** [comment]
Thanks Orion. I'll look into this and try to see what's going on!
If the group feel it would make life easier to allow empty arrays, then that's fine, but we will have to change the wording of the spec to allow for this. We should also include logical deifnitions. I'd love to do this myself, given my involvement in JSON Schema, but I'm really swamped with internal work, and will be for a while.

**Comment by Relequestual** [comment]
Looks like this issue will be closed with our next release. Turns out I was over protective. I protected against this in our code, but then additionally using JSON Schema validation. I've relaxed the JSON Schema validation, so this instance shouldn't cause a 400 after our next release.

**Comment by buske** [comment]
Are you using the same JSON schema as we have in the reference-server? Can we combine forces and put one in the mme-apis repo?

**Comment by Relequestual** [comment]
I am not because perl only has draft-3 support. I spent about 3-4 days trying to update to a new perl module which DOES support draft-4, but the error output is not useable for reporting errors back to API users.

I'm in discussion with the module author to see how easy this is to fix, but I'm not sure what the answer will be. The module mostly makes use of Type::Tiny for doing validation, and I couldn't see any way to access specific validation errors. I won't bore you by going into the details.

**Comment by Relequestual** [comment]
I do agree though, we should collaborate and get something into the repo. For your reference if you're wondering, draft-4 and 5 are basically the same, and makes a few changes, but support is limited as of yet.

**Comment by Relequestual** [comment]
This has (for some time) been fixed for DECIPHER.
Happy to accept a PR to clarify that this is a valid request / response format, and get this issue closed.

**Comment by fschiettecatte** [comment]
I would close the issue.
