### ISSUE TITLE
Terms in metrics endpoint

### ISSUE THREAD

**Issue by Relequestual** [ga4gh/mme-apis#152]
For 1.1, the metrics endpoint should have included `terms`, but only `disclaimer` was included.

For DECIPHER, we have a stipulation that we need to approave any use of the stats, and review any graphs or charts where they would be used, before presented.

**Comment by fschiettecatte** [comment]
Obviously an oversight, unless someone objects I can create a branch and pull request off master for this.

**Comment by Relequestual** [comment]
Quick fix and tag as 1.1.1 will be fine for this =]

**Comment by fschiettecatte** [comment]
Fixed and release created, I will leave it up to you to close the issue.
