### ISSUE TITLE
patienMatcher MME server

### ISSUE THREAD

**Issue by northwestwitch** [ga4gh/mme-apis#160]
Hi, I've created a MongoDB and Flask-based MME server to share patients sequenced at my institute (Clinical Genomics, Science For Life Laboratory, Stockholm). 
We are not connected to any other node yet, but we plan to do so after summer!

I was wondering if you might be interested to add our repo to the list of the available MME servers. Here's the link: https://github.com/Clinical-Genomics/patientMatcher

Thanks!

Cheers,
Chiara

**Comment by Relequestual** [comment]
Hey Chiara,

Thanks for getting in touch. I can see you've put in a lot of work into making your MME service! I know what that sort of effort looks like!

We only list fully fledged "Matchmaker Exchange Services" once they fully comply with the service requiremets.

We've documented this on the website by linking to a PDF of the requirements: http://www.matchmakerexchange.org/i_have_a_database.html

I'm only one of the technical people, so it would be great if you could email the group at api@matchmakerexchange.org so everyone hears about this! Most of the non-technical people in MME do not use github.

Cheers
Ben

**Comment by northwestwitch** [comment]
Thanks! I've written the software itself to be compliant with the requirements of the latest document (I remember that there were 3 points added a few months ago: exhaustive notifications, disclaimer and metrics so I've implemented those as well). 

The server we host at Clinical Genomics is not compliant of course because we are not connected to anyone yet, but maybe the software may be useful to someone else, it's open source.

Thanks for the suggestion, I will email the api group first thing after I'm back from the holidays, I am the only one working on this project in my lab and I might not be able to answer before the beginning of August.

Best,
Chiara

**Comment by northwestwitch** [comment]
Hello! I wanted to follow up on this. We are compliant with all points of the official requirements document except for the fact for the time being that we are connect to only one other node (MyGene2). But we're working on this and we'll be connected to other nodes soon. 

Thanks!
Chiara

**Comment by northwestwitch** [comment]
Closing this now, thanks again!
