### ISSUE TITLE
Using json-schema makes json format validate easier

### ISSUE THREAD

**Issue by Relequestual** [ga4gh/mme-apis#17]
Benjamin Hutton
12:41 10 Oct

I'm working on making validation really simple by creating a json-schema. The library I use also genereats a list of errors and which elements in the json do not validate, which I am including in the body of the response, with a status code of 400

Chris Mungall
02:21 30 Oct

Do you have the json-schema in a public repo? It would be useful to see this

Benjamin Hutton
12:04 3 Nov

Hi Chris. As our codebase is private, I can't clone or submodule just a single file out, so I have created a gist of the current version I've implemented. https://gist.github.com/Relequestual/f55783834a23b8837759

Chris Mungall
19:07 3 Nov

Thanks!

Orion Buske
23:36 6 Nov

Marked as resolved

Orion Buske
17:48 12 Nov

Re-opened
Pitching json-schema to GA4GH variation group. Seemed like positive response towards describing at least the RESTful nature as json-schema.

**Comment by Relequestual** [comment]
I don't know if you wanted to follow up on this Orion? =]

**Comment by buske** [comment]
Closing this. For the record, a json schema implementation of the MME v1.0 API can be found here: https://github.com/MatchmakerExchange/reference-server/blob/master/mme_server/schemas/api.json
