### ISSUE TITLE
Should we optionally specify if the variant is a CNV or SNV?

### ISSUE THREAD

**Issue by Relequestual** [ga4gh/mme-apis#54]
A search in Decipher for Intelectual Dissability will have a very large number of overlaps with specific genes. This should help combat the issue.

**Comment by buske** [comment]
I would argue that it is inconsistent with the spirit of the API to specify which fields to match on. Rather, I believe the goal should be to ensure that the API is able to represent patients with CNVs, SNVs, or both. It is then up to DECIPHER to decide how best to return matches, given that the request might have an SNV and you have other patients with CNVs, or both have CNVs, or whatnot. That's not to say that we can't add best-practices to the wiki, just that the control of *what to match on* should be left to the matchmaker, and the API should just be able to represent the information in a (request or response) patient. I realize that this is my soapbox so feel free to disagree. :)

As far as the current abilities of the API, I think it is currently possible to describe CNVs by referenceName/start/end/zygosity, but this could perhaps be improved. Thoughts?

**Comment by Relequestual** [comment]
I wasn't suggesting that this should be limited by the API in that fashion. My suggestion is to add a field in the request which says "I only wan't SNVs".

**Comment by Relequestual** [comment]
Closing because this doesn't fit with our query by example approach.
Note: Decipher may have many CNV results. It could be usful for parties receiving the data to allow users to filter the results by SNV or CNV.

**Comment by buske** [comment]
That's fair, I'm not sure what the best way to do matchmaking with CNVs is going to be. Was chatting with Kym today and she suggested avoiding CNV data for now. :/

**Comment by Relequestual** [comment]
That is sort of opposite to your previous comment, so I would have to dissagree.

Maybe we should include an optional field for the form of mutation. This would allow systems to filter out CNVs if they feel they want to.

It would be silly to rule out CNV data when a match could result in useful matches. We can't rule out that other parties may join with legacy CNV data which could be valuable. Heck, a useful match could result in the clinican seeking better resolution sequencing to update the patient record! I'd hate to exclude potentially useful data. Let's not forget, variants in DECIPHER have been chosen by the depositor to be the most likely cause of the recorded phenotypes; it's not the whole VCF file.
