### ISSUE TITLE
Look at use of ICHPT for translating between phenotype ontologies

### ISSUE THREAD

**Issue by Relequestual** [ga4gh/mme-apis#56]
ICHPT mappings have not yet been finalised or officially released.

We have been advised by Ada to wait for the paper and official website release (digestable format) of the mappings before seeking to implement usage.

**Comment by allasm** [comment]
Potentially related to #52

**Comment by buske** [comment]
Does this mean that we should remove ICHPT from the upcoming version of the API we're trying to release?

**Comment by fschiettecatte** [comment]
I am ok with removing it for now given that we are waiting on Peter for his input/blessing. I am not going to remove support from GeneMatcher since it is already in there, so we will accept ICHPT terms based on Ada's mappings, but we will only emit HPO.

**Comment by buske** [comment]
+1 

It's a backwards-compatible change to add it back in later, so I think we should remove it for now.

**Comment by Relequestual** [comment]
ICHPT has since been released!

Is there any system in MME that this would be benificial for?
ICHPT allows for mapping, but HPO is more descriptive! There's no reason a system can't get a copy of ICHPT (now) and then translate to their phenotype ontology of choosing that it supports.

**Comment by fschiettecatte** [comment]
It makes most sense to use HPO only for MME going forward. I don't think anyone has expressed an interest or need in using anything else. ICHPT has value but not for MME.

**Comment by Relequestual** [comment]
Voting to close this issue.

**Comment by fschiettecatte** [comment]
+1

**Comment by buske** [comment]
+1 Let's close this until groups have clear use cases that require it.

**Comment by buske** [comment]
Closing due to 3 votes.
