### ISSUE TITLE
Migrate v1.0 API to Avro

### ISSUE THREAD

**Issue by buske** [ga4gh/mme-apis#75]

**Comment by buske** [comment]
Created PR for current v1.0 version: https://github.com/ga4gh/schemas/pull/258

**Comment by Relequestual** [comment]
I have made a query on the pull request. Probably missing something but hey.

**Comment by buske** [comment]
This PR appears to still fit the v1.0a spec. If anyone else could take a look and confirm, I'd appreciate it. Thanks!

**Comment by Relequestual** [comment]
Has blocker of new requirements for ga4gh schemas.

**Comment by Relequestual** [comment]
Do we still want to do this? Does it have value? Is anyone going to look at the avro spec for MME, or is it a political tipping of the hat to ga4gh? If latter, we should close this, based on ga4gh schemas moving to protocol buffers.

**Comment by buske** [comment]
I think we should close this for now. If we decide we'd like to port the API to protobuf and satisfy all the requirements of integrating into the GA4GH APIs, we can create an issue then.
