### ISSUE TITLE
Ability to limit results returned

### ISSUE THREAD

**Issue by Relequestual** [ga4gh/mme-apis#86]
With new phenotype matching methods coming to light, Decipher will be performing an analysis score against all public patients in our database. That's still a large number!

I've had some thoughts to filter down the number of results.
Removing patients where the match score is less than 0.5, then also optionally only returning the top 10% of scores.

It's difficult to test the implications / actual uses of this till it gets used. However I have a suggestion for 1.1

Add an optional paramater for the request which is either, limit the returned results to a number, or a top percentage (where possible). OR. By default each system makes up their own mind about this, and an optional paramater is used to "return all".

Either way, this is down to the requesting system.

This thought is mostly aimed at requests which contain only phenotypic data, as genotypic data will be limited to scoring variants patients only.

**Comment by buske** [comment]
Related to #36.

I would vote for something akin to adding "maxResults" to the query, and "totalResults" to the response.

**Comment by Relequestual** [comment]
Hum. Yes, I see that's a good option! I think I'm trying to come up with a way which will allow us not to write end point specific code... at least for quering. Decipher will (probably) always return more matches than others for some queries.

Maybe we could go with the fields as you suggested, but it would be up to each group if they treat each end point the same or not. =]

**Comment by buske** [comment]
GA4GH looks like they're working on this as well: https://github.com/ga4gh/schemas/pull/246/files

They call it `pageSize`, and allow specifying a `pageToken` as well.

**Comment by fschiettecatte** [comment]
I am not keep on page tokens, requires the server to keep state which is what we got away from in Miami. I prefer the client to send a start and limit, and the server to include a max results in the response.

**Comment by Relequestual** [comment]
I agree. Having a page token sounds like an idea by someone who hasn't implemented such systems before. Also it wouldn't align with being RESTful.

**Comment by fschiettecatte** [comment]
@Relequestual Been there, done that, hence my lack of enthusiasm for page tokens.

**Comment by buske** [comment]
Good points. Completely agree with not having `pageToken`.

**Comment by Relequestual** [comment]
If we agree on this, let's add this to the 1.1 milestone?

**Comment by Relequestual** [comment]
Closing in favour of https://github.com/ga4gh/mme-apis/issues/36
